### PR TITLE
multicolor calculator

### PR DESCRIPTION
**Pull request by gauravrattan**
# Zero To Mastery - Webblocks 2022 📦📦

## PR contains: 
- best ui calculator 

## Breaking changes
none

## Screenshots
icon

### CODE REVIEW

**Comment by sophiabrandt** [comment]
Duplicate of #285 ?

If this is a new pull request, please branch from master/main.

It is hard to review if your PR contains several pull requests/duplicates.

**Comment by gauravrattan** [comment]
> Duplicate of #285 ?
> 
> If this is a new pull request, please branch from master/main.
> 
> It is hard to review if your PR contains several pull requests/duplicates.

**Comment by gauravrattan** [comment]
> Duplicate of #285 ?
> 
> If this is a new pull request, please branch from master/main.
> 
> It is hard to review if your PR contains several pull requests/duplicates.
its a new pull request from master

**Comment by gauravrattan** [comment]
it is my new project and new pull request from master 
pls review @sophiabrandt

**Comment by sophiabrandt** [comment]
Both https://github.com/zero-to-mastery/webblocks-2022/pull/294 and https://github.com/zero-to-mastery/webblocks-2022/pull/295 contain (partly) the same files, e.g., account.html. Please don't resubmit doubles, that makes it hard to review.

**Comment by sophiabrandt** [comment]
I can try to diff this differently. Nevermind.
But I need the licenses for the images, so that we can be sure that we don't violate copyright.

**Comment by sophiabrandt** [comment]
Maybe that's a problem with my browser, but I can only see 40 changed files with more than 1,700 changes. Maybe someone else can take a look.

**Comment by auxfuse** [comment]
@gauravrattan I'm not sure we can approve this PR. You have a sub-modules folder, and a bunch of images with no license attribution allocated. 

Can you give us some context as to the images and the submodules folder you have added to the directory?

**Comment by auxfuse** [comment]
I also think the best approach forward here would be to close these PRs, and then create each of them one at a time, with their own dedicated branch.

There is a lot of confusion here, and even more so...there is so much involved in your branch here that spans multiple features here, and not to mention the issue of the sub-modules folder and then the copyright licenses for the images. 😄 We would then be able to lend each PR the review they deserve, without having to worry about the other PRs that have all the same historical commits.

The PRs in question are: #294 #295 #296 <-- if each of these were closed without merging, and then recreating within their own branches with their own dedicated Commit history we should be good to review appropriately.

**Pull request closed without merging**
