### PR TITLE
Info box w/ Google maps embed

### PR DESCRIPTION
**Pull request by blitzmartin**
# Zero To Mastery - Webblocks 2022 📦📦

## PR contains:
This block is a container for some common **info and embedded Google map for a service** (restaurant, bar, sport center, office). It's built using simple HTML and CSS. Just change the placeholder with your details:

-Name of the service
-Full address
-Opening hours
-Phone number
-Website
-Embedded Google Maps link

## Breaking changes
None

## Screenshots
icon

### CODE REVIEW

**Comment by sophiabrandt** [comment]
We cannot accept PRs that use Node.js/`package.json`.

**Comment by blitzmartin** [comment]
In my project folder "blitzmartin-3" I only have:
-favicon.ico
-icon.PNG
-index.html
-styles.css
-meta.json (required in challange instructions)

**Comment by sophiabrandt** [comment]
For me, it shows changes to `package-lock.json` 
Screenshot_2022-10-23-21-17-09-38_4d38fce200f96aeac5e860e739312e76

**Comment by blitzmartin** [comment]
It was not in my folder, but in the top directory. I did not want to touch anything outside my project but anyway I have deleted it. I think I have pulled that package-lock.json when syncing the repo.

**Review by MattCSmith — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
