### PR TITLE
add a button that flies up like a rocket after the click

### PR DESCRIPTION
**Pull request by S44WN**
# Zero To Mastery - Webblocks 2022 📦📦

## PR contains:
- add a button that flies up like a rocket after the click

## Breaking changes
- None

## Screenshots
-
icon

### CODE REVIEW

**Comment by sophiabrandt** [comment]
Is this a duplicate of your previous pull requests? I see the same files over and over?
Currently your PRs are hard to review because if the code duplication.
If that's a new pull request, please branch from master/main and not your previous development branch.

**Comment by S44WN** [comment]
No, none of them are same.
All are different components as you can see in the screenshot.
And each component are on different branch.
I've done exactly as instructed in the main readme file and I also referred to the start-here-guidelines repo and also the video that was linked there.

**Comment by sophiabrandt** [comment]
Here again is the click button which is the same as in one of the other pull requests.
There are a lot of duplicates. Please make one pull request per artwork and don't resubmit all the others.

**Comment by sophiabrandt** [comment]
Looks like I cannot change the diff to a reasonable level. For me, it shows more than 2,000 lines changed in 9 commits, 40 files.
Screenshot_2022-10-23-21-31-42-52_4d38fce200f96aeac5e860e739312e76

Maybe someone else can take a look

**Comment by S44WN** [comment]
we are suppose to have 5 files each in one folder when we submit an artwork. 
So that 40 files means there is 8 artwork added and all are made on new/different branch.
It shows 40 files that are not on one PR but on 8, it shows an accumulation of unmerged contributions made by me.
Many lines changed is there because of the CSS files which are usually very lengthy.

those are changes from all the commits made by me. Each artwork has different PR and made on different branch

**Comment by sophiabrandt** [comment]
Sorry, but it looks to me as if these are 8 different _commits on the same branch_ instead of 8 _different branches_. This makes it very hard to review _for me_ (more than 2,797 lines 🤯 , reviewing 8 artworks in 1 pull request with more than 40 files).

I'm not 100% sure if Github offers a different diff view, I'm not using it in my day job, so maybe there's something one can adjust in the settings.

Example: Your artwork [Saawn - ClickButton](https://github.com/zero-to-mastery/webblocks-2022/tree/master/src/blocks/Saawn%20-%20ClickButton) is already merged, but it shows again for me on this PR, even though it is already merged into the master branch.

I will leave this to the other maintainers. This is a team effort, so I'm sure someone else can review this.

**Comment by S44WN** [comment]
hey, can you please check my repo that I forked of webblocks-2022 and made branches out of (as instructed in [start-here-guidelines](https://github.com/zero-to-mastery/start-here-guidelines)

branches on my forked repo here 
- [webblocks-2022](https://github.com/S44WN/webblocks-2022/branches/yours)
Screenshot (9)

**Comment by MattCSmith** [comment]
I'm not entirely sure what has happened here. 
@sophiabrandt is correct, this PR does contain all of your blocks, as does your other two pull requests. 
But I can see from your fork that you created the projects in separate branches. So I am not to sure why they have all been blended into the same PR. 

I will go ahead and merge this PR, but I suspect the other two PRs will then have conflicts meaning we wont be able to merge them.

**Pull request merged**
