### PR TITLE
Mainv

### PR DESCRIPTION
**Pull request by vmaineng**
# Zero To Mastery - Webblocks 2022 📦📦

👉 _**Please remove the below and replace with your own values, leaving the headers where they are.**_ 👈

## PR contains:
- INFO ABOUT YOUR PULL REQUEST GOES HERE (Please be as descriptive as possible) 🤜

## Breaking changes
- IF ANYTHING YOU'RE COMMITTING WOULD BREAK SOMETHING, INCLUDE HERE WHAT WOULD BREAK
- IF YOU HAVE NO BREAKING CHANGES, ENTER 'None'

## Screenshots
- IF YOU HAVE ANY SCREENSHOTS, INCLUDE THEM HERE.
- IF YOU HAVE NO SCREENSHOTS, ENTER 'None'

### CODE REVIEW

**Comment by vmaineng** [comment]
PR contains:
INFO ABOUT YOUR PULL REQUEST GOES HERE (Shotkallar715 playlist) 🤜
Breaking changes
None
Screenshots
icon

**Comment by vmaineng** [comment]
Final product

**Comment by sophiabrandt** [comment]
@vmaineng Please provide the licenses to the images and the music, so that we know that we don't violate copyright.

**Comment by vmaineng** [comment]
Hey Sophia,

There are no licenses to the images and the music, but I do have the
owner's permission. Is there something else I can provide from him granting
his permission?

**Comment by vmaineng** [comment]
Thanks so much for the help, Matt and Sophia! Do I need to do anything else
on my end?

**Pull request merged**
