### PR TITLE
Simple To Do List !

### PR DESCRIPTION
**Pull request by yashraj2003e**
<h1 dir="auto">Zero To Mastery - Webblocks 2022 <g-emoji class="g-emoji" alias="package" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4e6.png">package</g-emoji><g-emoji class="g-emoji" alias="package" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4e6.png">package</g-emoji></h1>

<h2>PR Contains -</h2>
<p><ul>Simple To Do List Using HTML,CSS and Javascript</ul></p>
<h2>Screenshot -</h2>
Screenshot

### CODE REVIEW

**Review by MattCSmith — CHANGES_REQUESTED** [review]
Hey you are missing the meta.json file. Checkout the readme for more information.

**Comment by yashraj2003e** [comment]
I have added, thank you.

**Review by MattCSmith — APPROVED** [review]
Looks good to me, nice job 👍

**Comment by yashraj2003e** [comment]
Thank You sir.

**Pull request merged**
