### PR TITLE
easy progress bar

### PR DESCRIPTION
**Pull request by DevTomilola-OS**
Simple progress bar with html,css and JS.

### CODE REVIEW

**Review by sirnotes — APPROVED** [review]
I haven’t tested this yet, but this looks good.

**Review by auxfuse — APPROVED** [review]
LGTM 🎉 Happy to merge 🙌 @sirnotes if you are?

**Comment by DevTomilola-OS** [comment]
Thank you so much.

**Comment by DevTomilola-OS** [comment]
Thank you so much.

**Comment by sirnotes** [comment]
Thank you for your contribution :D

**Pull request merged**
