### PR TITLE
Add CONTRIBUTING.md

### LINKED ISSUE #27: Add a CONTRIBUTING.md file
Screen Shot 2022-10-01 at 1 35 53 PM
I don't know if it is required, but I saw on the Hacktoberfest site that maintainers should add a CONTRIBUTING file as well as a Code of Conduct. 🙂

### PR DESCRIPTION
**Pull request by 0xSooki**
# Related Issues
[#27](https://github.com/zero-to-mastery/webblocks-2022/issues/27)
# Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the CONTRIBUTING document.
- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

# Description

Added CONTRIBUTING.md which makes it easier forhackroberfest participants to contribute

## Fixes #27 

# Screenshots/Recordings

# Added tests?

- [ ] Yes
- [x] No, because they aren't needed

# Added to documentation?

- [ ] README
- [x] Documentation
- [ ] No Documentation Needed

### CODE REVIEW

**Review by auxfuse — COMMENTED** [review]
This looks good to me! 🎉  However, while `CONTRIBUTING.md` files are an option for applicable repos taking part in Hacktoberfest. It isn't exactly necessary as everything here is already satisfied in the base `README.md`. I'm also a huge fan of the PR template used in this. Well done for adding that 🤜 

That being said, it's done well and if another Maintainer agrees with me we could merge this?

Tagging both @sirnotes @sophiabrandt in this for their input 😄

**Comment by 0xSooki** [comment]
Thank you, I appreciate your response :)

**Comment by sirnotes** [comment]
It's recommended to add a Contributing.md to the repo, so I'm okay with this :)

**Review by sirnotes — APPROVED** [review]

**Comment by sirnotes** [comment]
Looks like @sophiabrandt agrees as well. I will merge this.
re: https://github.com/zero-to-mastery/webblocks-2022/issues/27#issuecomment-1264642844

**Pull request merged**
