### PR TITLE
feat: responsive card with images that change on click

### PR DESCRIPTION
**Pull request by phylliswong**
# Zero To Mastery - Webblocks 2022 📦📦

## PR contains:
This PR contains a mobile responsive card for a travel site. The images change when you click them. All images are taken from the common space. 🤜

## Breaking changes
None

## Screenshots
Screen Shot 2022-10-18 at 10 33 33 AM
Screen Shot 2022-10-18 at 10 33 49 AM

### CODE REVIEW

**Comment by sophiabrandt** [comment]
@phylliswong what are the licenses for the images?

**Comment by phylliswong** [comment]
@sophiabrandt all images are taken from the common space. In future, is there somewhere in the code base where it is appropriate to add this?

**Comment by sophiabrandt** [comment]
@phylliswong I am not familiar with "the common space". Can you provide the licenses?
Images are usually under copyright, so unless it is from a page that has a permissive license (e.g., Unsplash.com), we cannot merge these pull requests, because we would violate copyright.

**Comment by phylliswong** [comment]
@sophiabrandt I've added the author and copyright block in the json. All images are free to use under Public Domain from Unsplash.

**Comment by sophiabrandt** [comment]
@phylliswong great, thank you.

**Pull request merged**
