### PR TITLE
conor-v switch box

### PR DESCRIPTION
**Pull request by conor-v**
my first webcomp for hacktoberfest 2022 - Switch box

### CODE REVIEW

**Review by auxfuse — CHANGES_REQUESTED** [review]
Hi @conor-v you have modified the original root `package-lock.json` file. Please resolve before we can approved and merge. Everything else appears to be fine.

**Comment by conor-v** [comment]
Do I just copy past the package.json from the main and push it again @auxfuse ?

**Comment by auxfuse** [comment]
Hi @conor-v if you just remove the file, and push back to your branch that should resolve it 😄 Thanks for getting back to us. 🤜

**Comment by conor-v** [comment]
Hey @auxfuse I think I did it.

**Review by auxfuse — APPROVED** [review]
Thanks for resolving @conor-v 🤜 Appreciate the patience! LGTM 😄

**Pull request merged**
