### PR TITLE
Blitzmartin branch

### PR DESCRIPTION
**Pull request by blitzmartin**
# Zero To Mastery - Webblocks 2022 📦📦

## PR contains:
This is a simple audio player with modern UI. 
It's built using HTML, CSS and JS. It loads songs from a local folder (included in the assets folder).
When you skip to next song, it autoplays. When you get to last song and skip to next, it goes back to first song.
With a conditional render, it shows play button or pause button depending if the song is playing or not.
The control buttons are made with Material Icons.
Songs in /assets/music are mine, hope you enjoy :)

## Breaking changes
None

## Screenshots
icon

### CODE REVIEW

**Review by MattCSmith — COMMENTED** [review]
What is the licensing for these music tracks?

**Comment by blitzmartin** [comment]
> What is the licensing for these music tracks?

There are a couple of covers I have recorded, rest of the music is mine. 
Should I add any messages regarding fair usage and copyright? I will delete the covers

**Comment by auxfuse** [comment]
@MattCSmith @blitzmartin Eveything seems to be fine with this, bar the licensing of the music. Could we consider replacing the music with copyright free tracks just to prove the concept of the feature, rather than have them linked to your covers?

**Comment by blitzmartin** [comment]
> @MattCSmith @blitzmartin Eveything seems to be fine with this, bar the licensing of the music. Could we consider replacing the music with copyright free tracks just to prove the concept of the feature, rather than have them linked to your covers?

There is no cover anymore, all the music is original and I am the only owner. I have already pushed the updated version but I don't know if I have to close this request and pull a different one.

**Comment by MattCSmith** [comment]
Awesome thanks, sounds good to me.

**Pull request merged**
