### PR TITLE
my web component

### PR DESCRIPTION
**Pull request by vishalpatil20**
A basic landing page to travel across various beach destination

### CODE REVIEW

**Comment by MattCSmith** [comment]
Hey @vishalpatil20 

Unfortunately I am unable to merge this PR as it deletes the example component. 
Could up updated you PR so that we can merge it  👍

**Review by MattCSmith — CHANGES_REQUESTED** [review]
Please do not delete other components

**Comment by vishalpatil20** [comment]
Yeah sure @MattCSmith i will get it done now

**Comment by vishalpatil20** [comment]
Hey @MattCSmith i have made the required changes plz do review it

**Comment by MattCSmith** [comment]
Awesome thanks 👍

**Pull request merged**
